server:
  port: 8084

spring:
  application:
    name: telemedicine-service
  datasource:
    url: jdbc:postgresql://localhost:5436/telemedicinedb
    username: health
    password: health
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

agora:
  app-id: ${AGORA_APP_ID:demo-app-id}
  app-certificate: ${AGORA_APP_CERTIFICATE:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-telemedicine:5432/telemedicinedb}
    username: ${SPRING_DATASOURCE_USERNAME:health}
    password: ${SPRING_DATASOURCE_PASSWORD:health}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
