server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5437/paymentdb
    username: health
    password: health
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

payhere:
  merchant-id: ${PAYHERE_MERCHANT_ID:}
  merchant-secret: ${PAYHERE_MERCHANT_SECRET:}
  sandbox: ${PAYHERE_SANDBOX:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-payment:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:health}
    password: ${SPRING_DATASOURCE_PASSWORD:health}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
