apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  POSTGRES_USER: adminuser
  RMQ_USER: guest
  JWT_EXPIRATION: "86400000"
---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: Dsproject123
  RMQ_PASSWORD: guest
  JWT_SECRET: 8e9df6466f8acabdc21c27cc84310d54026f8d38645fb8bfa923ba3ac425abf1
  PAYHERE_MERCHANT_ID: your_payhere_merchant_id
  PAYHERE_SECRET: your_payhere_secret
  NOTIFY_LK_USER_ID: your_notify_lk_id
  NOTIFY_LK_API_KEY: your_notify_lk_api_key
  BREVO_API_KEY: your_brevo_api_key
  GEMINI_API_KEY: AIzaSyCDIaHshOjavp2YNcRVq08CwrtVZldGPGs
