# kubectl create secret generic healthcare-secrets -n healthcare --from-literal=jwt-secret='YOUR_LONG_SECRET'
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare
type: Opaque
stringData:
  jwt-secret: "dev-change-me-use-at-least-32-bytes-secret-key!!"
  postgres-user-password: "health"
