apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: healthcaredsmediconnectreg.azurecr.io/mediconnect-admin-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: JAVA_OPTS
              value: "-Xmx192m -Xms128m"
            - name: DB_NAME
              value: "admin_db"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=require"
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
