apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: healthcaredsmediconnectreg.azurecr.io/mediconnect-ai-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "32Mi"
              cpu: "1m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: JAVA_OPTS
              value: "-Xmx128m -Xms64m"
            - name: DB_NAME
              value: "ai_db"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=require"
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
