apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: prescription-service
  template:
    metadata:
      labels:
        app: prescription-service
    spec:
      containers:
        - name: prescription-service
          image: healthcaredsmediconnectreg.azurecr.io/mediconnect-prescription-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: JAVA_OPTS
              value: "-Xmx96m -Xms64m"
            - name: DB_NAME
              value: "prescription_db"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=require"
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
---
apiVersion: v1
kind: Service
metadata:
  name: prescription-service
spec:
  selector:
    app: prescription-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
