apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: healthcaredsmediconnectreg.azurecr.io/mediconnect-telemedicine-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "320Mi"
              cpu: "300m"
          env:
            - name: JAVA_OPTS
              value: "-Xmx192m -Xms128m"
            - name: DB_NAME
              value: "telemedicine_db"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=require"
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secret
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
